package testDb;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import testDb.Person;
import testDb.Profession;

import testDb.PersonDao;
import testDb.ProfessionDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig personDaoConfig;
    private final DaoConfig professionDaoConfig;

    private final PersonDao personDao;
    private final ProfessionDao professionDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        personDaoConfig = daoConfigMap.get(PersonDao.class).clone();
        personDaoConfig.initIdentityScope(type);

        professionDaoConfig = daoConfigMap.get(ProfessionDao.class).clone();
        professionDaoConfig.initIdentityScope(type);

        personDao = new PersonDao(personDaoConfig, this);
        professionDao = new ProfessionDao(professionDaoConfig, this);

        registerDao(Person.class, personDao);
        registerDao(Profession.class, professionDao);
    }
    
    public void clear() {
        personDaoConfig.getIdentityScope().clear();
        professionDaoConfig.getIdentityScope().clear();
    }

    public PersonDao getPersonDao() {
        return personDao;
    }

    public ProfessionDao getProfessionDao() {
        return professionDao;
    }

}
